### ISSUE TITLE
error in VTK package

### ISSUE THREAD

**Issue by MohamadHalwani** [danielTobon43/pcl_visualizer#1]
I'm not sure what the issue is but when the code reaches the visualization section a segmentation error is there !
I tried removing the line you added that removes the errors. 
and the following error appeared !
```
Generic Warning: In /build/vtk6-McbzXj/vtk6-6.2.0+dfsg1/Rendering/OpenGL/vtkOpenGLPolyDataMapper.cxx, line 69
vtkOpenGLPolyDataMapper::vtkOpenGLPolyDataMapper was deprecated for VTK 6.2 and will be removed in a future version.

Segmentation fault (core dumped)
```
Do you have any idea ?

**Comment by ghost** [comment]
Hi @MohamadHalwani .

Could you please share a screenshot of your output? Because if there is a "segmentation fault" error, could be something after or before the vtk line.

I used that line to remove the vtk warning, but the warning is not causing to crash the program. Have you checked if the input file is following the pipeline, what type of file are you using?

**Comment by MohamadHalwani** [comment]
Its a .pcd file, 
this is exactly what I'm getting, I'm sure its from this line because I tried printing "111" before it and "222" after the line, 
as you can see only 111 appeared.
```
111
Generic Warning: In /build/vtk6-McbzXj/vtk6-6.2.0+dfsg1/Rendering/OpenGL/vtkOpenGLPolyDataMapper.cxx, line 69
vtkOpenGLPolyDataMapper::vtkOpenGLPolyDataMapper was deprecated for VTK 6.2 and will be removed in a future version.

Segmentation fault (core dumped)

```

**Comment by ghost** [comment]
@MohamadHalwani ok, so what is the output before removing the line and after?

**Comment by MohamadHalwani** [comment]
Exactly the same output but without the warning.
So,
```
111

Segmentation fault (core dumped)
```

**Comment by ghost** [comment]
> Exactly the same output but without the warning.
> 
> So,
> 
> ```
> 
> 111
> 
> 
> 
> Segmentation fault (core dumped)
> 
> ```
> 
> 

@MohamadHalwani ok. So the vtk line is working properly. Let's try this: Comment everything after the vtk line and run the program and let me know if the program is still crashing

**Comment by MohamadHalwani** [comment]
you mean commenting the following section ? 
```
vtkObject::GlobalWarningDisplayOff(); // Disable vtk render warning         
  boost::shared_ptr<pcl::visualization::PCLVisualizer> viewer (new pcl::visualization::PCLVisualizer ("PCL VISUALIZER"));

  viewer->setPosition(0,0);
  viewer->setBackgroundColor(0.0, 0.0, 0.0, 0.0); // Setting background to a dark grey

  viewer->setShowFPS(false);

  viewer->addCoordinateSystem();
  pcl::PointXYZ p1, p2, p3;

  p1.getArray3fMap() << 1, 0, 0;
  p2.getArray3fMap() << 0, 1, 0;
  p3.getArray3fMap() << 0,0.1,1;

  viewer->addText3D("x", p1, 0.2, 1, 0, 0, "x_");
  viewer->addText3D("y", p2, 0.2, 0, 1, 0, "y_");
  viewer->addText3D ("z", p3, 0.2, 0, 0, 1, "z_");

  std::string str = "Points: ";
  std::stringstream ss;
  ss << cloud->points.size();
  str += ss.str();

  int xpos = 1.0;
  int ypos = 1.0;
  int fontSize = 13;

  double r = 1.0;
  double g = 1.0;
  double b = 1.0;

  viewer->addText(str, xpos, ypos, fontSize,r,g,b,"text1");

  if(cloud->points[0].r <= 0 and cloud->points[0].g <= 0 and cloud->points[0].b<= 0 ){
      pcl::visualization::PointCloudColorHandlerCustom<pcl::PointXYZRGB> color_handler(cloud,255,255,0);
      viewer->removeAllPointClouds(0);
      viewer->addPointCloud(cloud,color_handler,"POINTCLOUD");
  }else{
      viewer->addPointCloud(cloud,"POINTCLOUD");
  }
  
  viewer->initCameraParameters();
  viewer->resetCamera();

  pcl::console::print_info ("\npress [q] to exit!\n");

  while(!viewer->wasStopped()){
      viewer->spin();
  }


  return 0;
}

```
The program is not crashing but I think it won't visualize anything if the visualizer is not defined ?

**Comment by ghost** [comment]
@MohamadHalwani ok perfect, exactly, the program won't show you the point cloud, but we have found the problem. It seems is related to the pcl-visualizer object using the boost pointer. This could be 2 things:

1. You have a different boost version
2. You have a different pcl version

What i am guessing is that, you can try to change the pointer. 

Use this pointer:

pcl::visualization::PCLVisualizer::Ptr viewer (new pcl::visualization::PCLVisualizer ("3D Viewer"));

( remember to uncomment everything)

**Comment by MohamadHalwani** [comment]
Thank you, its working now :+1:

**Comment by ghost** [comment]
@MohamadHalwani Wonderful. Don't forget to close the "issue" forum
